import type { McpServerEntry } from "./types"

export const mcpServers: McpServerEntry[] = [
  {
    key: "better-t-stack",
    label: "Better T Stack",
    name: "better-t-stack",
    target: "npx create-better-t-stack@latest mcp",
    when: { deps: ["*"] },
  },
  {
    key: "context7",
    label: "Context7",
    name: "context7",
    target: "@upstash/context7-mcp",
    when: { deps: ["*"] },
  },
  {
    key: "nx",
    label: "Nx Workspace",
    name: "nx",
    target: "npx nx mcp .",
    when: { deps: ["nx"] },
  },
  {
    key: "cloudflare-docs",
    label: "Cloudflare Docs",
    name: "cloudflare-docs",
    target: "https://docs.mcp.cloudflare.com/sse",
    transport: "sse",
    when: { deps: ["wrangler", "@cloudflare/workers-types"] },
  },
  {
    key: "convex",
    label: "Convex",
    name: "convex",
    target: "npx -y convex@latest mcp start",
    when: { deps: ["convex"] },
  },
  {
    key: "shadcn",
    label: "shadcn/ui",
    name: "shadcn",
    target: "npx -y shadcn@latest mcp",
    when: { deps: ["react-router-dom", "@tanstack/react-router", "@tanstack/start", "next"] },
  },
  {
    key: "next-devtools",
    label: "Next Devtools",
    name: "next-devtools",
    target: "npx -y next-devtools-mcp@latest",
    when: { deps: ["next"] },
  },
  {
    key: "nuxt-docs",
    label: "Nuxt Docs",
    name: "nuxt",
    target: "https://nuxt.com/mcp",
    when: { deps: ["nuxt"] },
  },
  {
    key: "nuxt-ui-docs",
    label: "Nuxt UI Docs",
    name: "nuxt-ui",
    target: "https://ui.nuxt.com/mcp",
    when: { deps: ["nuxt"] },
  },
  {
    key: "svelte-docs",
    label: "Svelte Docs",
    name: "svelte",
    target: "https://mcp.svelte.dev/mcp",
    when: { deps: ["svelte"] },
  },
  {
    key: "astro-docs",
    label: "Astro Docs",
    name: "astro-docs",
    target: "https://mcp.docs.astro.build/mcp",
    when: { deps: ["astro"] },
  },
  {
    key: "planetscale",
    label: "PlanetScale",
    name: "planetscale",
    target: "https://mcp.pscale.dev/mcp/planetscale",
    when: { deps: ["@planetscale/database"] },
  },
  {
    key: "neon",
    label: "Neon",
    name: "neon",
    target: "https://mcp.neon.tech/mcp",
    when: { deps: ["@neondatabase/serverless"] },
  },
  {
    key: "supabase",
    label: "Supabase",
    name: "supabase",
    target: "https://mcp.supabase.com/mcp",
    when: { deps: ["@supabase/supabase-js"] },
  },
  {
    key: "better-auth",
    label: "Better Auth",
    name: "better-auth",
    target: "https://mcp.inkeep.com/better-auth/mcp",
    when: { deps: ["better-auth"] },
  },
  {
    key: "clerk",
    label: "Clerk",
    name: "clerk",
    target: "https://mcp.clerk.com/mcp",
    when: { deps: ["@clerk/nextjs", "@clerk/clerk-react", "@clerk/express", "@clerk/backend"] },
  },
  {
    key: "expo",
    label: "Expo",
    name: "expo-mcp",
    target: "https://mcp.expo.dev/mcp",
    when: { deps: ["expo"] },
  },
  {
    key: "polar",
    label: "Polar",
    name: "polar",
    target: "https://mcp.polar.sh/mcp/polar-mcp",
    when: { deps: ["@polar-sh/sdk"] },
  },
]
