// export { mcpServers } from "./registry/mcp-servers"
// export { skills } from "./registry/skills"
// export type { McpServerEntry, SkillEntry, WhenCondition, McpTransport } from "./registry/types"
// export { detectDeps } from "./services/detector/detector"
// export { matchMcpServers, matchSkills } from "./matcher"
// export type { ResolvedSkillEntry } from "./matcher"
